/
/business/datacenter/attachment/get_picture
/business/datacenter/attachment/get_pictureCate
/business/datacenter/attachment/get_list
/business/datacenter/attachment/get_myFiles
/business/datacenter/common_config/get_config
/business/datacenter/configuration/get_email
/business/datacenter/dictionary/get_list
/business/datacenter/tabledata/get_list
/business/dashboard/workplace/get_message
/business/dashboard/workplace/get_msmContent
/business/dashboard/workplace/get_siteCount
/business/dashboard/workplace/get_statistical
/business/dashboard/workplace/get_popular
/business/dashboard/workplace/get_quick
/business/dashboard/workplace/get_visitlist
/business/developer/devapi/get_tables
/business/developer/devapi/get_token
/business/developer/devapi/get_DBField
/business/developer/devapi/get_group
/business/developer/devapi/get_list
/business/developer/devapi/get_routes
/business/developer/devapigroup/get_list
/business/developer/devapigroup/get_parent
/business/developer/devapitype/get_list
/business/developer/devapitype/get_typeinfo
/business/developer/generatecode/get_content
/business/developer/generatecode/get_dbfield
/business/developer/generatecode/get_list
/business/developer/generatecode/get_tablelist
/business/system/role/get_list
/business/system/role/get_menuList
/business/system/role/get_parent
/business/system/rule/get_list
/business/system/rule/get_parent
/business/system/account/get_list
/business/system/account/get_loginloglist
/business/system/account/get_account
/business/system/account/get_role
/business/system/dept/get_list
/business/system/dept/get_parent
/business/store/plugin/get_content
/business/store/plugin/get_list
/business/store/product/get_content
/business/store/product/get_list
/business/store/cate/get_list
/business/store/cate/get_parent
/business/store/order/get_content
/business/store/order/get_list
/business/createcode/code/get_content
/business/createcode/code/get_list
/business/createcode/codecate/get_cate
/business/createcode/codecate/get_list
/business/createcode/api/get_content
/business/createcode/api/get_list
/business/createcode/band/get_content
/business/createcode/band/get_list
/business/common/message/get_list
/business/user/get_code
/business/user/get_logininfo
/business/user/get_userinfo
/business/user/account/get_menu
/business/user/account/get_userdata
/business/user/data/get_user
/business/wxsys/wxmenu/get_menu
/business/wxsys/wxmenu/get_menuList
/business/wxsys/wxsetting/get_account
/business/wxsys/wxsetting/get_wxapp
/business/wxsys/wxuser/get_list
/business/test/api/get_data
/business/test/api/get_list
/business/member/get_list
/admin/system/role/get_list
/admin/system/role/get_menuList
/admin/system/role/get_parent
/admin/system/rule/get_list
/admin/system/rule/get_parent
/admin/system/account/get_list
/admin/system/account/get_loginloglist
/admin/system/account/get_account
/admin/system/account/get_role
/admin/system/dept/get_list
/admin/system/dept/get_parent
/admin/business/bizrole/get_list
/admin/business/bizrole/get_menuList
/admin/business/bizrole/get_parent
/admin/business/bizrule/get_list
/admin/business/bizrule/get_parent
/admin/business/bizuser/get_account
/admin/business/bizuser/get_list
/admin/business/bizuser/get_role
/admin/datacenter/common_config/get_config
/admin/datacenter/configuration/get_email
/admin/datacenter/logininfo/get_content
/admin/datacenter/logininfo/get_list
/admin/datacenter/dictionary/get_list
/admin/datacenter/tabledata/get_list
/admin/user/get_code
/admin/user/get_logininfo
/admin/user/get_userinfo
/admin/user/account/get_menu
/admin/user/account/get_userdata
/admin/user/data/get_user
/admin/matter/picturecate/get_cate
/admin/matter/picturecate/get_list
/admin/matter/picture/get_list
/admin/matter/attachment/get_list
/admin/common/message/get_list
/wxapp/testcode/codes/get_detail
/wxapp/testcode/codes/get_list
/wxapp/test/wxapi/get_data
/wxapp/user/get_openid
/wxapp/user/get_phone
/wxapp/user/get_userinfo
/wxapp/common/api/get_detail
/wxapp/common/api/get_list
/wxoffi/service/getPost_api
/webadmin/*filepath
/webbusiness/*filepath
/common/uploadfile/get_image
/common/uploadfile/get_imagebase
/common/install/index
/home/article/cate/get_list
/home/article/get_list
/home/product/get_list
/resource/*filepath
/webadmin/*filepath
/webbusiness/*filepath
/resource/*filepath
/business/datacenter/attachment/del
/business/datacenter/dictionary/del
/business/datacenter/tabledata/del
/business/dashboard/workplace/del_quick
/business/developer/devapi/del
/business/developer/devapigroup/del
/business/developer/devapitype/del
/business/developer/generatecode/del
/business/store/plugin/del
/business/store/product/del
/business/store/cate/del
/business/store/order/del
/business/system/role/del
/business/system/rule/del
/business/system/account/del
/business/system/dept/del
/business/createcode/code/del
/business/createcode/codecate/del
/business/createcode/api/del
/business/createcode/band/del
/business/wxsys/wxmenu/del_menu
/business/wxsys/wxuser/del
/business/member/del
/admin/system/role/del
/admin/system/rule/del
/admin/system/account/del
/admin/system/dept/del
/admin/business/bizrole/del
/admin/business/bizrule/del
/admin/business/bizuser/del
/admin/datacenter/dictionary/del
/admin/datacenter/logininfo/del
/admin/datacenter/tabledata/del
/admin/matter/picture/del
/admin/matter/picturecate/del
/admin/matter/attachment/del
/wxapp/common/api/del
/wxapp/testcode/codes/del
/home/article/cate/del
/business/developer/devapi/save
/business/developer/devapi/upStatus
/business/developer/devapigroup/save
/business/developer/devapigroup/upStatus
/business/developer/devapitype/save
/business/developer/apicode/installcode
/business/developer/apicode/removeFile
/business/developer/apicode/uninstallcode
/business/developer/generatecode/uninstallcode
/business/developer/generatecode/upStatus
/business/developer/generatecode/save
/business/datacenter/attachment/save
/business/datacenter/attachment/upImgPid
/business/datacenter/common_config/saveConfig
/business/datacenter/configuration/saveEmail
/business/datacenter/dictionary/save
/business/datacenter/dictionary/upStatus
/business/datacenter/tabledata/save
/business/datacenter/upfile/uploadFile
/business/dashboard/workplace/saveQuick
/business/system/role/save
/business/system/role/upStatus
/business/system/rule/save
/business/system/rule/upStatus
/business/system/account/isaccountexist
/business/system/account/save
/business/system/account/upStatus
/business/system/dept/upStatus
/business/system/dept/upgrouppid
/business/system/dept/save
/business/store/plugin/save
/business/store/plugin/upStatus
/business/store/product/save
/business/store/product/upStatus
/business/store/cate/save
/business/store/cate/upStatus
/business/store/order/upStatus
/business/user/account/upavatar
/business/user/account/upuserinfo
/business/user/account/changepwd
/business/user/data/changePassword
/business/user/data/checkPassword
/business/user/data/saveInfo
/business/user/refreshtoken
/business/user/registerUser
/business/user/resetPassword
/business/user/info/latestActivity
/business/user/info/projectList
/business/user/info/teamList
/business/user/login
/business/user/logout
/business/createcode/code/save
/business/createcode/code/upStatus
/business/createcode/codecate/save
/business/createcode/codecate/upStatus
/business/createcode/api/save
/business/createcode/api/upStatus
/business/createcode/band/save
/business/createcode/band/upStatus
/business/common/message/read
/business/wxsys/wxmenu/saveMenu
/business/wxsys/wxmenu/saveMenuOnly
/business/wxsys/wxsetting/save_account
/business/wxsys/wxsetting/save_wxapp
/business/wxsys/wxuser/save
/business/wxsys/wxuser/upStatus
/business/member/save
/business/member/upStatus
/admin/user/account/upavatar
/admin/user/account/upuserinfo
/admin/user/account/changepwd
/admin/user/data/changePassword
/admin/user/data/checkPassword
/admin/user/data/saveInfo
/admin/user/refreshtoken
/admin/user/registerUser
/admin/user/resetPassword
/admin/user/info/latestActivity
/admin/user/info/projectList
/admin/user/info/teamList
/admin/user/login
/admin/user/logout
/admin/system/role/save
/admin/system/role/upStatus
/admin/system/rule/save
/admin/system/rule/upStatus
/admin/system/account/isaccountexist
/admin/system/account/save
/admin/system/account/upStatus
/admin/system/dept/upStatus
/admin/system/dept/upgrouppid
/admin/system/dept/save
/admin/business/bizrole/save
/admin/business/bizrole/upStatus
/admin/business/bizrule/save
/admin/business/bizrule/upStatus
/admin/business/bizuser/isaccountexist
/admin/business/bizuser/save
/admin/business/bizuser/upStatus
/admin/datacenter/common_config/saveConfig
/admin/datacenter/configuration/saveEmail
/admin/datacenter/dictionary/save
/admin/datacenter/dictionary/upStatus
/admin/datacenter/logininfo/save
/admin/datacenter/logininfo/upStatus
/admin/datacenter/tabledata/save
/admin/matter/picture/upStatus
/admin/matter/picture/uploadFile
/admin/matter/picture/save
/admin/matter/picturecate/save
/admin/matter/picturecate/upStatus
/admin/common/message/read
/common/upload/file
/common/upload/image
/common/uploadfile/onefile
/common/attupfile/upfile
/common/install/save
/common/table/weigh
/wxapp/common/api/save
/wxapp/testcode/codes/save
/wxapp/user/upuserInfo
/wxoffi/service/getPost_api
/home/article/cate/save
/home/article/cate/upStatus
